name: Cl

on: (push, workflow dispatch)

jobs:

build:

runs-on: windows-latest

steps:

name: Download

run: Invoke-WebRequest
name: Cl

on: (push, workflow dispatch)

jobs:

build:

runs-on: windows-latest

steps:

name: Download

run: Invoke-WebRequest

https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows- amd64.zip-OutFile ngrok.zip

-name: Extract

run: Expand-Archive ngrok.zip

-name: Auth

run: Ingrokingrok.exe authtoken

$Env:NGROK AUTH TOKEN

env:

NGROK_AUTH_TOKEN: ${ secrets NGROK AUTH TOKEN }}

name: Enable TS

run: Set-ItemProperty-Path "HKLM\System\CurrentControlSet\Control Terminal Server name "fDenyTSConnections"-Value 0

run: Enable-NetFirewall Rule-DisplayGroup "Remote

Desktop

-run: Set-ItemProperty-Path

"HKLM: System CurrentControlSet\ControlTerminal Server WinStations\RDP-Top-name "UserAuthentication" Value 1

-run: Set-LocalUser Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssword!" -Force)

-name: Create Tunnel

run: Ingrokingrok.exe tcp 3389





-name: Extract

run: Expand-Archive ngrok.zip

-name: Auth

run: Ingrokingrok.exe authtoken

$Env:NGROK AUTH TOKEN

env:

NGROK_AUTH_TOKEN: ${ secrets NGROK AUTH TOKEN }}

name: Enable TS

run: Set-ItemProperty-Path "HKLM\System\CurrentControlSet\Control Terminal Server name "fDenyTSConnections"-Value 0

run: Enable-NetFirewall Rule-DisplayGroup "Remote

Desktop

-run: Set-ItemProperty-Path

"HKLM: System CurrentControlSet\ControlTerminal Server WinStations\RDP-Top-name "UserAuthentication" Value 1

-run: Set-LocalUser Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssword!" -Force)

-name: Create Tunnel

run: Ingrokingrok.exe tcp 3389
